FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libfontconfig \
    && curl https://grafanarel.s3.amazonaws.com/builds/grafana_{{ grafana_version }}_amd64.deb -o /tmp/grafana.deb \
    && dpkg -i /tmp/grafana.deb \
    && usermod -a -G microservices grafana \
    && chown -R grafana: /etc/grafana \
    && rm /tmp/grafana.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER grafana
